In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving Loan_default_prediction.csv to Loan_default_prediction.csv

In [ ]:
df = pd.read_csv('Loan_default_prediction.csv')
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [ ]:
df.shape

(2999, 18)

In [ ]:
df['Default'].mean()

np.float64(0.1237079026342114)

In [ ]:
df.groupby('LoanPurpose')['Default'].mean()

LoanPurpose
Auto         0.121464
Business     0.130053
Education    0.124585
Home         0.103503
Other        0.140234
Name: Default, dtype: float64

pandas groupby = SQL GROUP BY

In [ ]:
df[df['Income']>50000]

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
5,A9S62RQ7US,25,90298,90448,720,18,2,22.72,24,0.10,High School,Unemployed,Single,Yes,No,Business,Yes,1
6,H8GXPAOS71,38,111188,177025,429,80,1,19.11,12,0.16,Bachelor's,Unemployed,Single,Yes,No,Home,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,BRYJU6JNNM,66,126094,177099,554,11,1,19.91,60,0.48,Bachelor's,Self-employed,Married,No,No,Business,No,1
2995,25SWN6MN82,38,84120,132382,548,96,1,13.99,60,0.56,PhD,Unemployed,Single,No,No,Home,No,1
2996,T1OLOPDQDX,52,99629,86409,575,110,4,19.35,36,0.73,PhD,Part-time,Single,Yes,Yes,Home,No,0
2997,AFO6U7AK8Z,49,118365,107915,438,37,4,24.15,12,0.47,High School,Self-employed,Divorced,No,Yes,Education,Yes,0
2998,WRBUH95HNY,47,91796,43994,304,96,3,6.60,36,0.81,Master's,Part-time,Divorced,No,Yes,Business,Yes,0

1.Task one ->show only rows where CreditScore < 600

In [ ]:
df[df['CreditScore']<600]

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
6,H8GXPAOS71,38,111188,177025,429,80,1,19.11,12,0.16,Bachelor's,Unemployed,Single,Yes,No,Home,Yes,0
7,0HGZQKJ36W,56,126802,155511,531,67,4,8.15,60,0.43,PhD,Full-time,Married,No,No,Home,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,BRYJU6JNNM,66,126094,177099,554,11,1,19.91,60,0.48,Bachelor's,Self-employed,Married,No,No,Business,No,1
2995,25SWN6MN82,38,84120,132382,548,96,1,13.99,60,0.56,PhD,Unemployed,Single,No,No,Home,No,1
2996,T1OLOPDQDX,52,99629,86409,575,110,4,19.35,36,0.73,PhD,Part-time,Single,Yes,Yes,Home,No,0
2997,AFO6U7AK8Z,49,118365,107915,438,37,4,24.15,12,0.47,High School,Self-employed,Divorced,No,Yes,Education,Yes,0
2998,WRBUH95HNY,47,91796,43994,304,96,3,6.60,36,0.81,Master's,Part-time,Divorced,No,Yes,Business,Yes,0

2.Groupby: recreate your (average default rate by income bracket)

In [ ]:
df['IncomeBracket'] = df['Income'].apply(lambda x: 'Low' if x < 70000 else ('Medium' if x < 100000 else 'High'))
df.groupby(['IncomeBracket'])['Default'].mean()*100

IncomeBracket
High      10.582960
Low       14.435484
Medium    11.490683
Name: Default, dtype: float64

3. Combine filter + groupby: average default rate by LoanPurpose, but only for loans where LoanAmount > 100000

In [ ]:
df[df['LoanAmount']> 100000].groupby(['LoanPurpose'])['Default'].mean()*100

LoanPurpose
Auto         14.247312
Business     12.500000
Education    15.926893
Home         12.010444
Other        15.656566
Name: Default, dtype: float64

4.Recreate your Q1 (overall default rate) using .mean() directly on the Default column

In [ ]:
df['Default'].mean()*100

np.float64(12.37079026342114)